### ISSUE TITLE
Internal links on /builds/README.md don't work

### ISSUE THREAD

**Issue by sdruskat** [singularityhub/singularityhub-docs#2]
The links under *Building Options* on https://singularityhub.github.io/singularityhub-docs/docs/builds don't work in production, as they miss the `/builds/` part of the path. E.g., https://singularityhub.github.io/singularityhub-docs/docs/automated doesn't work, whereas the correct link (as in the TOC) https://singularityhub.github.io/singularityhub-docs/docs/builds/automated does.

Interestingly, this doesn't show in a local serve I've just done from master, where the link `[Deployment Build](deployment)` resolves correctly to http://127.0.0.1:4000/singularityhub-docs/docs/builds/deployment.

This is strange behaviour. Is the live version of the docs built from master?

**Comment by vsoch** [comment]
huh, I didn't notice that! Let me give it a quick test locally - usually the relative path just needs to be used from the file (so build/<path> would be the fix).

**Comment by sdruskat** [comment]
Cool. `builds/<path>`, right?

**Comment by vsoch** [comment]
hey @sdruskat I think I fixed it! It was relatively simple - I needed to add a trailing slash to builds. Do you want to test it out?

https://singularityhub.github.io/singularityhub-docs/docs/builds/

I'll look over the other pages and make changes now.

**Comment by vsoch** [comment]
Ok just pushed more fixes! Give GitHub pages a few minutes to update, and then ensure that your cache is disabled (open devtools and check the box to disable cache when it's open)

And thank you so kindly for catching this! It's really strange that it works locally, and I should have tested online. I suspect that my local machine was doing some sort of cache for the page, but who knows.

**Comment by sdruskat** [comment]
Ace, the ones I stumbled over work fine now!

**Comment by vsoch** [comment]
Great! Thanks again for pointing this out.
