### ISSUE TITLE
Resolve discrepancy in usage documentation

### ISSUE THREAD

**Issue by sdruskat** [singularityhub/singularityhub-docs#4]
In the *Image interaction* section of the docs, it says that

```
You should never issue any of the following commands

singularity run shub://vsoch/hello-world
singularity shell shub://vsoch/hello-world
singularity exec shub://vsoch/hello-world ls /
```

However, if you look at the *Usage* page in the shub UI (btw, IMHO the titling suggests access to usage stats), it implicitly warns to not use containers directly from shub as each run is 1/100 downloads. It goes on, however, to only give that exact example in the "Run a container" section of the page.

![image](https://user-images.githubusercontent.com/3007126/62602613-68207780-b8f4-11e9-9d8c-189fcf596727.png)

I think it'd be good to separate the different concerns of the page a little better.

Concern 1) seems to be to present all options for interacting with shub from the CLI, so it *does* make sense to include the *Run a container* example with a run command using shub directly.

Concern 2) is "hidden" in the warning box on top, i.e., presenting the best practice of pulling first, then using the local version.

I'd suggest getting rid of the warning box and introducing a "best practice" section that includes the info from the box + gives a simple example along the lines of, e.g.,

```
# First, pull the container from Singularity Hub
singularity pull shub://sdruskat/getpapers-singularity

# Then interact with it
singularity run getpapers_singularity 
[NOTE I'm not actually sure what the container would be named, as I haven't built and pulled one yet, I guess getpapers_singularity_latest?)
```

What do you think?

**Comment by vsoch** [comment]
I completely agree - the page could use a clean up to better reflect the new suggested practices (and link to them!) How's this? https://singularity-hub.org/collections/1223/usage

**Comment by sdruskat** [comment]
Great, much better. Thanks!

**Comment by vsoch** [comment]
Sure thing! I'm going to close the issue, ping me if there is more to discuss.
